import pickle

APP_TITLE = 'Word Chain'

GUI_STRINGS = {
    'WORD_LABEL': 'Word',
    'MESSAGE_LABEL': 'Messages',
    'CHALLENGE_BUTTON': 'Challenge',
    'NEW_GAME_BUTTON': 'New Game',
    'PLAY_LETTER_BUTTON': 'Play',
    'QUIT_BUTTON': 'Quit'
}

GAME_STATES = {
    'HUMAN_PLAY': 1,
    'HUMAN_CHALLENGED': 2,
    'COMPUTER_PLAY': 3,
    'COMPUTER_CHALLENGED': 4,
    'GAME_OVER': 5
}
with open('../res/word_list.pkl', 'rb') as f:
    WORD_LIST = pickle.load(f)

ICON = b'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAAAXNSR0IArs4c6Q' \
       b'AAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAPcSURBVHhe' \
       b'7d0xUttQFEBRO1vKAmhZVQrWB2siBa4yTEKMJOv9e06DSvz+uyMYa+zr0/PrBa' \
       b'p+3H5CkgBIEwBpAiBNAKQJgDQBkCYA0gRAmgBIEwBpAiBNAKQJgDQBkCYA0gRA' \
       b'mgBIEwBpAiBNAKQJgDQBkCYA0gRAmgBIEwBpAiBNAKQJgDQBkCYA0gRAmgBIEw' \
       b'BpAiBNAKQJgDQBkCYA0nxR9jauv37ervbx/vJ2u2JT7gCkCYA0AXTt/WfbCAJI' \
       b'00AuAEf+h/hAWgHY/k+VxxIKwPb/RXY4lQBs/z81R5QIwPZ/UXBQ6wdg+/9LbV' \
       b'yLB2D775Aa2soB2P67dUa3bAC2/5siA1wzANu/icIYFwzA9m9o+WGuFoDt39za' \
       b'I10qANu/k4UHu04Atn9Xq453kQBs/wGWHPIKAdj+w6w36vEB2P6DLTbw2QHY/o' \
       b'dYaeyDA7D9D7TM8KcGYPsfbo0jGBmA7T+JBQ5iXgC2/1SmH8ewAGz/CY0+lEkB2' \
       b'P7Tmns0YwKw/Sc39IBmBGD7R5h4TAMCsP2DjDusswdg+8eZdWSnDsD2DzXo4M4b' \
       b'gO3nACcNwPZzjAH/BMN+BECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0' \
       b'ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmANA' \
       b'GQJgDSBEDa9en59Xa5jxN+2dH7y9vtajt7v8yJv/N+NpyGOwBpAiBNAKQJgDQBk' \
       b'CYA0gRAmgBIEwBpAiBNAKQJgLRvPQw39GkqD8N9ONXx7fECv8IdgDQBkCYA0gRA' \
       b'mgBIEwBpAiBNAKR5I2wb3gg70obTcAcgzecCbcMd4EjuALANAZAmANIEQJoASBM' \
       b'AaQIgTQCkCYA0AZAmANJ2fxboPrs+puJZoA/jhrwHdwDSBECaAEgTAGkCIE0ApA' \
       b'mANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJ' \
       b'gDSBECaAEgTAGkCIK346dAcwKdDwwACIE0ApAmANAGQJgDSBECaAEgTAGkCIE0A' \
       b'pAmANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmANAG' \
       b'QJgDSBECaAEgTAGkCIE0ApAmAtJN+SR4cwx2ANAGQJgDSBECaAEgTAGkCIE0ApA' \
       b'mANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmANAGQJ' \
       b'gDSBECaAEgTAGkCIE0ApAmANAGQJgDSBECaAEgTAGkCIE0ApAmAsMvlNz/ka//J' \
       b'JvOyAAAAAElFTkSuQmCC'
